image: python:3

deploy:
  environment: production
  only:
    - tags
  before_script:
     # Set up the virtualenv
    - pip install virtualenv
    - virtualenv env
    - source ./env/bin/activate

    # Install node
    - wget https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-x64.tar.xz -O /tmp/node.tar.xz
    - tar xf /tmp/node.tar.xz -C /opt
    - export PATH=/opt/node-v6.11.1-linux-x64/bin/:$PATH

  script:
    - npm install
    # Deploy
    - ./node_modules/.bin/sls deploy
